FROM node:11.5.0

ARG APP_ID
ARG APP_SECRET
ARG CONNECT_URL
ARG HTTP_PORT
ARG NODE_ENV
ARG NODE_ENV
ARG CS_JS_SDK_URL
ARG CS_AC_SHIM_URL

ENV APP_ID $APP_ID
ENV APP_SECRET $APP_SECRET
ENV CONNECT_URL $CONNECT_URL
ENV HTTP_PORT $HTTP_PORT
ENV CS_JS_SDK_URL $CS_JS_SDK_URL
ENV CS_AC_SHIM_URL $CS_AC_SHIM_URL


WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN yarn install --silent

COPY . /usr/src/app
RUN yarn build

CMD ["yarn","start"]

